defmodule MyApp.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_token, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    alter table(:user_account) do
      modify :username, :citext
      add :hashed_password, :text, null: false
    end

    create unique_index(:user_account, [:username], name: "user_account_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:user_account, [:username],
                     name: "user_account_unique_username_index"
                   )

    alter table(:user_account) do
      remove :hashed_password
      modify :username, :text
    end

    drop table(:user_token)
  end
end